version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  tscApp:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: # run tests
          name: Typescript checking
          command: cd app && npm run tsc
  tscApi:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: # run tests
          name: Typescript checking
          command: cd api && npm run tsc

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: # run tests
          name: Testing
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - tscApp:
          requires:
            - build
      - tscApi:
          requires:
            - build
      - test:
          requires:
            - build
